// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWrrjsyT9fN7KlbJ3CS3-Qh_8QUP0gtdU',
    appId: '1:1075752688678:web:bb9b3e86215614ea0adae7',
    messagingSenderId: '1075752688678',
    projectId: 'cloud-messaging-4cd9a',
    authDomain: 'cloud-messaging-4cd9a.firebaseapp.com',
    storageBucket: 'cloud-messaging-4cd9a.firebasestorage.app',
    measurementId: 'G-LFNNZH3LPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCePbrJzEn_CRVP7gxXWZya-PQ0pDE0Du4',
    appId: '1:1075752688678:android:806f18739917ec120adae7',
    messagingSenderId: '1075752688678',
    projectId: 'cloud-messaging-4cd9a',
    storageBucket: 'cloud-messaging-4cd9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLSDK2EifZFmONB8GgcevQHdcK1OvtdpQ',
    appId: '1:1075752688678:ios:15e4f2bca0c9d83f0adae7',
    messagingSenderId: '1075752688678',
    projectId: 'cloud-messaging-4cd9a',
    storageBucket: 'cloud-messaging-4cd9a.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLSDK2EifZFmONB8GgcevQHdcK1OvtdpQ',
    appId: '1:1075752688678:ios:15e4f2bca0c9d83f0adae7',
    messagingSenderId: '1075752688678',
    projectId: 'cloud-messaging-4cd9a',
    storageBucket: 'cloud-messaging-4cd9a.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWrrjsyT9fN7KlbJ3CS3-Qh_8QUP0gtdU',
    appId: '1:1075752688678:web:a66a88bfca65cce20adae7',
    messagingSenderId: '1075752688678',
    projectId: 'cloud-messaging-4cd9a',
    authDomain: 'cloud-messaging-4cd9a.firebaseapp.com',
    storageBucket: 'cloud-messaging-4cd9a.firebasestorage.app',
    measurementId: 'G-PKMELM8KTL',
  );
}
